
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        telp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        P = new javax.swing.JRadioButton();
        L = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Thunder Lord", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTACT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 10, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 60);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setText("no. telp");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 230, 110, 30);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setText("nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 70, 110, 30);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel4.setText("jns kelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 110, 110, 30);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel5.setText("alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 150, 110, 30);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(350, 70, 380, 30);

        telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpActionPerformed(evt);
            }
        });
        getContentPane().add(telp);
        telp.setBounds(350, 230, 380, 30);

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 150, 380, 70);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nama", "jk", "alamat", "telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 240, 230);

        jButton2.setText("hapus kontak");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 270, 110, 30);

        jButton3.setText("tambah kontak");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 270, 170, 30);

        jButton4.setText("refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(530, 270, 80, 30);

        buttonGroup1.add(P);
        P.setText("P");
        getContentPane().add(P);
        P.setBounds(430, 110, 50, 30);

        buttonGroup1.add(L);
        L.setText("L");
        getContentPane().add(L);
        L.setBounds(350, 110, 50, 30);

        jButton5.setText("ubah");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(440, 270, 80, 30);

        setSize(new java.awt.Dimension(755, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int baris = tblData.getSelectedRow();
        if (baris != -1)
        {
            String nama = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_data WHERE nama='"+nama+"'";
            int status = koneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DIHAPUS", "SUKSES!", JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                JOptionPane.showMessageDialog(this, "DATA GAGAL DIHAPUS", "GAGAL!", JOptionPane.WARNING_MESSAGE);
            }
        }else
        {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin Anda hapus terlebih dahulu!", "ERROR!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String JK = "";
            if (L.isSelected())
            {
                JK = "L";
            }
            if (P.isSelected())
            {
                JK = "P";
            }
        
        if("".equals(nama.getText()) || "".equals(JK) || "".equals(alamat.getText()) || "".equals(telp.getText()))
        {
            JOptionPane.showMessageDialog(this, "ANDA HARUS MELENGKAPI DATA", "Error", JOptionPane.WARNING_MESSAGE);
        }else
        {
            String SQL = "INSERT INTO tb_data (nama,jk,alamat,telp) "
                    + "VALUES('"+nama.getText()+"',"
                    + "'"+JK+"','"+alamat.getText()+"','"+telp.getText()+"')";
            int status = koneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DITAMBAHKAN", "SUKSES!", JOptionPane.INFORMATION_MESSAGE);
                {
                    selectData();
                }
            }else
            {
                JOptionPane.showMessageDialog(this, "DATA GAGAL DITAMBAHKAN", "GAGAL!", JOptionPane.WARNING_MESSAGE);
            }
        }     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        selectData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String JK = "";
            if (L.isSelected())
            {
                JK = "L";
            }
            if (P.isSelected())
            {
                JK = "P";
            }
        
        if("".equals(nama.getText()) || "".equals(JK) || "".equals(alamat.getText()) || "".equals(telp.getText()))
        {
            JOptionPane.showMessageDialog(this, "ANDA HARUS MELENGKAPI DATA", "Error", JOptionPane.WARNING_MESSAGE);
        }else
        { 
            String SQL = "UPDATE tb_data SET "
                    + "jk='"+JK+"', alamat='"+alamat.getText()+"' "
                    + "telp='"+telp.getText()+"' "
                    + "WHERE nama='"+nama.getText()+"'";          
            int status = koneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DIUPDATE", "SUKSES!", JOptionPane.INFORMATION_MESSAGE);
                {
                    selectData();
                }
            }else
            {
                JOptionPane.showMessageDialog(this, "DATA GAGAL DIUPDATE", "GAGAL!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if(baris != -1)
        {
            nama.setText(tblData.getValueAt(baris, 0).toString());
            if("Laki-laki".equals(tblData.getValueAt(baris, 1).toString()))
            {
                L.setSelected(true);
            }else
            {
                P.setSelected(true);
            }
            
            alamat.setText(tblData.getValueAt(baris, 2).toString());
            telp.setText(tblData.getValueAt(baris, 3).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton L;
    private javax.swing.JRadioButton P;
    private javax.swing.JTextArea alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nama;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField telp;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"nama","jk","alamat","telp"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_data";
        ResultSet rs = koneksiDB.executeQuery(SQL);
        try
        {
            while(rs.next())
            {
                String nama = rs.getString(1);
                String JenisKelamin = "";
                if("L".equals(rs.getString(2)))
                {
                    JenisKelamin = "Laki-laki";
                }else
                {
                    JenisKelamin = "Perempuan";
                }
                String alamat = rs.getString(3);
                String telp = rs.getString(4);
                String data[] = {nama,JenisKelamin,alamat,telp};
                dtm.addRow(data);
            }
        }catch (SQLException ex)
        {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}
